# Generated by Django 6.0.5 on 2026-05-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('tipo_cuenta', models.CharField(max_length=50, verbose_name='Tipo de cuenta')),
                ('numero_cuenta', models.CharField(max_length=50, verbose_name='Número de cuenta')),
                ('titular', models.CharField(max_length=120, verbose_name='Titular de la cuenta')),
                ('identificacion', models.CharField(blank=True, max_length=20, verbose_name='Cédula o RUC')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo del titular')),
                ('nota', models.TextField(blank=True, verbose_name='Nota adicional')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Dato de pago',
                'verbose_name_plural': 'Datos de pago',
            },
        ),
    ]
