# Generated by Django 6.0.5 on 2026-05-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_datospago'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospago',
            name='mensaje_whatsapp',
            field=models.TextField(blank=True, default='Hola, deseo realizar una consulta sobre Innova Food.', verbose_name='Mensaje inicial de WhatsApp'),
        ),
        migrations.AddField(
            model_name='datospago',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de WhatsApp'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Interés aplicado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago_credito',
            field=models.BooleanField(default=False, verbose_name='Pago a crédito'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal_sin_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_compra',
            field=models.CharField(choices=[('menor', 'Compra al por menor'), ('mayor', 'Compra al por mayor')], default='menor', max_length=20, verbose_name='Tipo de compra'),
        ),
    ]
