# Generated by Django 6.0.5 on 2026-05-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_datospago_mensaje_whatsapp_datospago_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_presentacion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad de presentación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('ml', 'Mililitros'), ('l', 'Litros'), ('g', 'Gramos'), ('kg', 'Kilogramos')], default='unidad', max_length=20, verbose_name='Unidad de medida'),
        ),
    ]
