# Generated by Django 6.0.5 on 2026-05-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_cantidad_presentacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospago',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, verbose_name='Número de WhatsApp'),
        ),
    ]
